using System;
using NUnit.Framework;
using Test1;

namespace Test1.Tests
{
    [TestFixture]
    public class MyTestClass49
    {
        [Test]
        public void TestDoTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Test2DoTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}