using System;
using NUnit.Framework;
using TestValid;

namespace TestValid.Tests
{
    [TestFixture]
    public class MyTestClass67
    {
        [Test]
        public void ValidDoTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}